# Generated by Django 4.2.6 on 2025-04-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('business_value', models.FloatField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('company_website', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=25, null=True)),
                ('industry_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_internation', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
                ('create_user', models.CharField(max_length=50)),
                ('create_user_id', models.BigIntegerField()),
                ('last_updated_date', models.DateTimeField()),
                ('last_updated_user', models.CharField(max_length=50)),
                ('last_updated_user_id', models.BigIntegerField()),
                ('version_lock', models.BigIntegerField(blank=True, null=True)),
                ('customer_manager_id', models.BigIntegerField(blank=True, null=True)),
                ('bom_margin_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='assignedmilestone',
            name='assignBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignBy',null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedmilestone',
            name='customerName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignedmilestone',
            name='customprojectName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
