# Generated by Django 4.2.6 on 2025-04-18 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Timeline', '0002_customer_assignedmilestone_assignby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedmilestone',
            name='customerCode',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='assignedmilestone',
            name='quoted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignedmilestone',
            name='systemName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedmilestone',
            name='assignBy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
