# Generated by Django 4.2.6 on 2025-04-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0003_assignedmilestone_customercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetsubmission',
            name='assigId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Timeline.assignedmilestone'),
        ),
    ]
