# Generated by Django 4.2.6 on 2025-04-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0004_timesheetsubmission_assigid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='assignBy',
        ),
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='customerCode',
        ),
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='customprojectName',
        ),
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='quoted_date',
        ),
        migrations.RemoveField(
            model_name='assignedmilestone',
            name='systemName',
        ),
        migrations.RemoveField(
            model_name='timesheetsubmission',
            name='assigId',
        ),
    ]
