# Generated by Django 4.2.6 on 2025-04-18 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Timeline', '0005_remove_assignedmilestone_assignby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation', models.CharField(db_index=True, max_length=50)),
                ('customprojectName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('systemName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('customerName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('customerCode', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('quoted_date', models.DateField(default=django.utils.timezone.now)),
                ('project', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('projectName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('milestone', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('milestoneName', models.CharField(blank=True, max_length=100, null=True)),
                ('task', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('taskName', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assignBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignBy', to=settings.AUTH_USER_MODEL)),
                ('assignTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignTo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Task',
                'verbose_name_plural': 'Assigned Tasks',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timeline.assignedtask')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'indexes': [models.Index(fields=['assignId', 'date'], name='Timeline_su_assignI_51316f_idx'), models.Index(fields=['assignId', 'status'], name='Timeline_su_assignI_7e3db8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['quotation', 'milestone'], name='Timeline_as_quotati_56fbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assignTo', 'quotation'], name='Timeline_as_assignT_462866_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assignTo', 'start_date', 'end_date'], name='Timeline_as_assignT_7e3ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['assignTo', 'project', 'milestone', 'task'], name='Timeline_as_assignT_9e36e2_idx'),
        ),
    ]
