# Generated by Django 4.2.6 on 2025-04-20 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Timeline', '0006_assignedtask_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetstatus',
            name='action_by',
        ),
        migrations.AddField(
            model_name='submission',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheetstatus',
            name='unlock_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheetstatus',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
