# Generated by Django 4.2.6 on 2025-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0007_remove_timesheetstatus_action_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetstatus',
            name='unlock_request',
        ),
        migrations.AddField(
            model_name='timesheetstatus',
            name='unlock_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=10),
        ),
    ]
