# Generated by Django 4.2.6 on 2025-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0008_remove_timesheetstatus_unlock_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetstatus',
            name='unlock_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=None, max_length=10),
        ),
    ]
