# Generated by Django 5.0.8 on 2025-07-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0010_alter_timesheetstatus_unlock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetstatus',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetstatus',
            name='unlock_status',
            field=models.CharField(choices=[('Requested', ''), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=None, max_length=10, null=True),
        ),
    ]
