# Generated by Django 5.0.8 on 2025-07-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0011_timesheetstatus_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetsubmission',
            name='uid',
        ),
        migrations.DeleteModel(
            name='AssignedMilestone',
        ),
        migrations.DeleteModel(
            name='TimesheetSubmission',
        ),
    ]
