# Generated by Django 5.0.8 on 2025-10-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupsRole',
            new_name='GroupRole',
        ),
    ]
