# Generated by Django 5.0.8 on 2025-10-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_groupsrole_grouprole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jobtitles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.grouprole'),
            preserve_default=False,
        ),
    ]
