# Generated by Django 5.0.8 on 2025-10-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_users_jobtitles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='jobtitles',
            new_name='jobtitle',
        ),
    ]
