# Generated by Django 5.0.8 on 2025-10-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_rename_jobtitles_users_jobtitle'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupRole',
            new_name='JobTitles',
        ),
        migrations.RemoveField(
            model_name='pagegroup',
            name='group',
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='jobtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employee.jobtitles'),
            preserve_default=False,
        ),
    ]
