# Generated by Django 5.0.8 on 2025-10-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_rename_grouprole_jobtitles_remove_pagegroup_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitles',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.role'),
        ),
        migrations.AlterField(
            model_name='users',
            name='jobtitle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.jobtitles'),
        ),
    ]
