# Generated by Django 5.0.8 on 2025-10-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_jobtitles_role_alter_users_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude', models.BooleanField(default=False)),
                ('dailyEmail', models.BooleanField(default=False)),
                ('weeklyEmail', models.BooleanField(default=False)),
                ('unlockLongTerm', models.BooleanField(default=False)),
                ('hoursRestriction', models.BooleanField(default=False)),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.jobtitles')),
            ],
        ),
    ]
