# Generated by Django 5.0.8 on 2025-10-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_otherpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitles',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.role'),
        ),
    ]
