# Generated by Django 5.0.8 on 2025-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_jobtitles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpermissions',
            name='notSubmittedSummaryMail',
            field=models.BooleanField(default=False),
        ),
    ]
