# Generated by Django 5.0.8 on 2025-11-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_otherpermissions_notsubmittedsummarymail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherpermissions',
            old_name='exclude',
            new_name='excludeAllMail',
        ),
    ]
