# Generated by Django 5.0.8 on 2025-11-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_rename_exclude_otherpermissions_excludeallmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherpermissions',
            old_name='excludeAllMail',
            new_name='otherMails',
        ),
    ]
