# Generated by Django 5.0.8 on 2025-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_rename_excludeallmail_otherpermissions_othermails'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpermissions',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
