# Generated by Django 5.0.8 on 2025-11-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_otherpermissions_exclude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpermissions',
            name='otherMails',
        ),
        migrations.RemoveField(
            model_name='otherpermissions',
            name='unlockLongTerm',
        ),
    ]
