# Generated by Django 5.0.8 on 2025-11-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_remove_otherpermissions_othermails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
