"""
Django settings for ProDesk project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@djp#l@i@%-llc!a#w=ryl)r2rz!%ol-s__0-(!s!lxazn*!f_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  True

# CSRF_TRUSTED_ORIGINS = ["http://192.168.5.23"]
ALLOWED_HOSTS = ["*"]  # Or specify only necessary domains
# CORS_ALLOWED_ORIGINS = ["http://192.168.5.23"]
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = False

# ALLOWED_HOSTS = ['tsm.icpro.in'] 
# CSRF_TRUSTED_ORIGINS = ["https://tsm.icpro.in"]
# CSRF_ALLOWED_ORIGINS = ["https://tsm.icpro.in"]
# CORS_ORIGINS_WHITELIST = ["https://tsm.icpro.in"]
# 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #User Defined Apps
    'Employee',
    'Projects',
    'Timeline',
    'Analysys',
    'Settings',
    'Documents'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ProDesk.urls'

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug':DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    }
]

WSGI_APPLICATION = 'ProDesk.wsgi.application'

AUTH_USER_MODEL = 'Employee.users'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'tsm-erp',
    #     'USER':'root',
    #     'PASSWORD':'Wiretrone@123$',
    #     'HOST':'15.207.178.193', #'localhost',
    #     'PORT':'3306',
    #     'STORAGE_ENGINE': 'MyISAM / INNODB / ETC'
    # },
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'erp': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'icpro_prod',
        'USER':'readonlyprod',
        'PASSWORD':'Icpro@123$',
        'HOST':'13.235.232.202',
        'PORT':'9101',
        'STORAGE_ENGINE': 'MyISAM / INNODB / ETC',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 60,
            'read_timeout': 60,
            'write_timeout': 60,
        },
        'CONN_MAX_AGE': 300,  # Keep connections open for 5 minutes
    }
}
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL =  '/static/'
# STATIC_ROOT = BASE_DIR / 'static'
# STATIC_ROOT = os.path.join(BASE_DIR,'static') #This is the directory  where the static files are collected

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#Mediafiles
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#SMTP Configuration

EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'icproprojects@gmail.com'
EMAIL_HOST_PASSWORD = 'nlureawcucoybcub'

# Login URLS
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"


# SESSION AGE 5 Minutes
# TIME= 15*60 #four hours  or your time
# SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
# SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
# SESSION_EXPIRE_AT_BROWSER_CLOSE= True
# SESSION_COOKIE_AGE = TIME    #change expired session
# SESSION_IDLE_TIMEOUT = TIME  #logout
# SESSION_TIMEOUT_REDIRECT = 'home'

# wkhtmltopdf
# WKHTMLTOPDF_PATH = os.path.join(BASE_DIR,'/minutes_of_meetings/generate_pdf/wkhtmltopdf')
