# Generated by Django 4.2.6 on 2025-03-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_free_text', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateTimeField()),
                ('create_user', models.CharField(max_length=50)),
                ('create_user_id', models.BigIntegerField()),
                ('last_updated_date', models.DateTimeField()),
                ('last_updated_user', models.CharField(max_length=50)),
                ('last_updated_user_id', models.BigIntegerField()),
                ('version_lock', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostMaster',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateTimeField()),
                ('create_user', models.CharField(max_length=50)),
                ('create_user_id', models.BigIntegerField()),
                ('last_updated_date', models.DateTimeField()),
                ('last_updated_user', models.CharField(max_length=50)),
                ('last_updated_user_id', models.BigIntegerField()),
                ('version_lock', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Settings.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='phaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(default='')),
                ('phases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Settings.phases')),
            ],
        ),
    ]
