# Generated by Django 5.0.8 on 2024-11-21 08:34

import Documents.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='document_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='', max_length=100)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('version', models.CharField(default='', max_length=10)),
                ('file', models.FileField(storage=Documents.storage.OverwriteStorage(), upload_to='document/')),
            ],
        ),
        migrations.CreateModel(
            name='feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('Description', models.CharField(default='', max_length=500)),
                ('file', models.FileField(storage=Documents.storage.OverwriteStorage(), upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='lessonlearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=100)),
                ('Event', models.CharField(max_length=500)),
                ('Limitations', models.CharField(max_length=500)),
                ('Actions', models.CharField(max_length=500)),
                ('file_lesson', models.FileField(blank=True, default=None, null=True, storage=Documents.storage.OverwriteStorage(), upload_to='lessonlearnt/')),
                ('Status', models.CharField(max_length=50)),
                ('Remark', models.CharField(max_length=500)),
            ],
        ),
    ]
