# Generated by Django 5.0.8 on 2025-06-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestions',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
