# Generated by Django 5.0.8 on 2025-06-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_suggestion_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='remarks',
            field=models.CharField(default=None, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestions',
            field=models.CharField(blank=True, default=None, max_length=1500),
        ),
    ]
